export type CauldronSpace = {
  shopPoints: number
  victoryPoints: number
  hasRuby?: boolean
}

export const cauldronSpaces: CauldronSpace[] = [
  { shopPoints: 0, victoryPoints: 0 },
  { shopPoints: 1, victoryPoints: 0 },
  { shopPoints: 2, victoryPoints: 0 },
  { shopPoints: 3, victoryPoints: 0 },
  { shopPoints: 4, victoryPoints: 0 },
  { shopPoints: 5, victoryPoints: 0, hasRuby: true },
  { shopPoints: 6, victoryPoints: 1 },
  { shopPoints: 7, victoryPoints: 1 },
  { shopPoints: 8, victoryPoints: 1 },
  { shopPoints: 9, victoryPoints: 1, hasRuby: true },
  { shopPoints: 10, victoryPoints: 2 },
  { shopPoints: 11, victoryPoints: 2 },
  { shopPoints: 12, victoryPoints: 2 },
  { shopPoints: 13, victoryPoints: 2, hasRuby: true },
  { shopPoints: 14, victoryPoints: 3 },
  { shopPoints: 15, victoryPoints: 3 },
  { shopPoints: 15, victoryPoints: 3, hasRuby: true },
  { shopPoints: 16, victoryPoints: 3 },
  { shopPoints: 16, victoryPoints: 4 },
  { shopPoints: 17, victoryPoints: 4 },
  { shopPoints: 17, victoryPoints: 4, hasRuby: true },
  { shopPoints: 18, victoryPoints: 4 },
  { shopPoints: 18, victoryPoints: 5 },
  { shopPoints: 19, victoryPoints: 5 },
  { shopPoints: 19, victoryPoints: 5, hasRuby: true },
  { shopPoints: 20, victoryPoints: 5 },
  { shopPoints: 20, victoryPoints: 6 },
  { shopPoints: 21, victoryPoints: 6 },
  { shopPoints: 21, victoryPoints: 6, hasRuby: true },
  { shopPoints: 22, victoryPoints: 7 },
  { shopPoints: 22, victoryPoints: 7, hasRuby: true },
  { shopPoints: 23, victoryPoints: 7 },
  { shopPoints: 23, victoryPoints: 8 },
  { shopPoints: 24, victoryPoints: 8 },
  { shopPoints: 24, victoryPoints: 8, hasRuby: true },
  { shopPoints: 25, victoryPoints: 9 },
  { shopPoints: 25, victoryPoints: 9, hasRuby: true },
  { shopPoints: 26, victoryPoints: 9 },
  { shopPoints: 26, victoryPoints: 10 },
  { shopPoints: 27, victoryPoints: 10 },
  { shopPoints: 27, victoryPoints: 10, hasRuby: true },
  { shopPoints: 28, victoryPoints: 11 },
  { shopPoints: 28, victoryPoints: 11, hasRuby: true },
  { shopPoints: 29, victoryPoints: 11 },
  { shopPoints: 29, victoryPoints: 12 },
  { shopPoints: 30, victoryPoints: 12 },
  { shopPoints: 30, victoryPoints: 12, hasRuby: true },
  { shopPoints: 31, victoryPoints: 12 },
  { shopPoints: 31, victoryPoints: 13 },
  { shopPoints: 32, victoryPoints: 13 },
  { shopPoints: 32, victoryPoints: 13, hasRuby: true },
  { shopPoints: 33, victoryPoints: 14 },
  { shopPoints: 33, victoryPoints: 14, hasRuby: true },
]
